version: "3.9"

services:
  backend:
    build: ./career_intelligence_backend
    ports:
      - "8000:8000"
    env_file:
      - ./career_intelligence_backend/.env

  frontend:
    build: ./career_intelligence_frontend
    ports:
      - "3000:3000"
    env_file:
      - ./career_intelligence_frontend/.env.local
    depends_on:
      - backend
